name: Deploy server

on:
  push:
    paths:
      - "apps/server/**"
      - "packages/common/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu@ec2-54-167-241-231.compute-1.amazonaws.com "sudo bash /home/ubuntu/sold-store-2/apps/server/deploy.sh"
